### ISSUE TITLE
filter_jp_file.py doesn't work with corrected output

### ISSUE THREAD

**Issue by etwatson** [gibsonMatt/jaltomataQTL#1]
Hi, thanks for sharing your approach to the stacks R/qtl output problem. I'm not great at python, so I thought I would mention a curiosity about your filter_jp_file.py script. 

It works like a charm if the corrections flag, -c is not passed to the genotypes program. For some reason, when corrections are made, I get the following error:

python filter_jp_file.py -i joinmap -v -ot rqtl -f ./corrected.loc -t 20 -o test 
02/22:10:24:32AM Filtering markers. Minimum # of individuals calls = 20
02/22:10:24:32AM Removing 623 markers
02/22:10:24:32AM File number of markers = 2667
02/22:10:24:32AM Exporting to rqtl format...
**Traceback (most recent call last):
  File "filter_jp_file.py", line 190, in <module>
    main(*sys.argv)
  File "filter_jp_file.py", line 182, in main
    rqtlOutput(newDict, out2, nloc, nind, indvNames)
  File "filter_jp_file.py", line 84, in rqtlOutput
    genotypesByIndv[individuals[i]].append(calls[i])
IndexError: list index out of range**

I can't see any obvious difference between the corrected and uncorrected joinmap files, except the genotype corrections and number of loci. The problem is with rqtlOutput() as joinmapOutput() works just fine.

**Comment by gibsonMatt** [comment]
Thanks for noticing. If I remember correctly I ran into the same problem. Would it be helpful to you if I fixed this issue?
